name: vpython colab
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - numpy==1.26.4
    - jupyterlab==4.1.5
    - notebook==7.1.2
    - vpython==7.6.5
    - jupyter-collaboration==2.0.5
