name: vpython colab
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - jupyterlab==4.1.4
    - notebook==7.1.1
    - jupyterlab-vpython==3.1.8
    - vpython==7.6.5b5
    - jupyter-collaboration
